[package]
name = "kairos-time"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
publish = false

[dependencies]
freenet-stdlib = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bs58 = { workspace = true }
hex = { workspace = true }
ed25519-compact = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["freenet-main-contract"]
freenet-main-contract = []
contract = ["freenet-stdlib/contract"]

[dev-dependencies]
ed25519-dalek = { workspace = true, features = ["rand_core"] }
